/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ControllerUtils;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.MaskFormatter;
import javax.swing.text.DefaultFormatterFactory;
import org.json.JSONObject;

/**
 *
 * @author User
 */
public class GUICadFornecedor extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarFornecedor
     */
    public GUICadFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioTipoPessoa = new javax.swing.ButtonGroup();
        alertaCancelar = new javax.swing.JDialog();
        panelAlerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelDados = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        boxNome = new javax.swing.JTextField();
        lemail = new javax.swing.JLabel();
        lcep = new javax.swing.JLabel();
        boxEmail = new javax.swing.JTextField();
        boxCEP = new javax.swing.JTextField();
        panelCPF = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        boxRG = new javax.swing.JTextField();
        try{
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            txtData = new javax.swing.JFormattedTextField(mascara);
            boxCPF_CNPJ = new javax.swing.JFormattedTextField();
            radioCNPJ = new javax.swing.JRadioButton();
            radioCPF = new javax.swing.JRadioButton();
            jPanel1 = new javax.swing.JPanel();
            boxUF = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            jLabel8 = new javax.swing.JLabel();
            boxCidade = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            boxBairro = new javax.swing.JTextField();
            jLabel10 = new javax.swing.JLabel();
            boxLogradouro = new javax.swing.JTextField();
            buttonCancelar = new javax.swing.JButton();
            buttonCadastrar = new javax.swing.JButton();
            buttonBuscarEm = new javax.swing.JButton();

            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("<html><body>Deseja cancelar o cadastro do fornecedor? <br> Todo o processo será apagado.</body></html>");
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

            jButton1.setText("Não");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Sim");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout panelAlertaLayout = new javax.swing.GroupLayout(panelAlerta);
            panelAlerta.setLayout(panelAlertaLayout);
            panelAlertaLayout.setHorizontalGroup(
                panelAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlertaLayout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(57, 57, 57))
                .addGroup(panelAlertaLayout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(97, 97, 97)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            panelAlertaLayout.setVerticalGroup(
                panelAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAlertaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2))
                    .addContainerGap(18, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout alertaCancelarLayout = new javax.swing.GroupLayout(alertaCancelar.getContentPane());
            alertaCancelar.getContentPane().setLayout(alertaCancelarLayout);
            alertaCancelarLayout.setHorizontalGroup(
                alertaCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAlerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            alertaCancelarLayout.setVerticalGroup(
                alertaCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            setAutoscrolls(true);
            setLayout(null);

            panelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do fornecedor"));
            panelDados.setLayout(null);

            lNome.setText("Nome:");
            panelDados.add(lNome);
            lNome.setBounds(11, 27, 37, 16);

            boxNome.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    boxNomeActionPerformed(evt);
                }
            });
            panelDados.add(boxNome);
            boxNome.setBounds(90, 25, 420, 22);

            lemail.setText("E-mail:");
            panelDados.add(lemail);
            lemail.setBounds(11, 157, 39, 16);

            lcep.setText("CEP:");
            panelDados.add(lcep);
            lcep.setBounds(11, 200, 28, 16);
            panelDados.add(boxEmail);
            boxEmail.setBounds(87, 154, 420, 20);

            boxCEP.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    boxCEPActionPerformed(evt);
                }
            });
            panelDados.add(boxCEP);
            boxCEP.setBounds(87, 194, 420, 22);

            jLabel5.setText("RG:");

            jLabel6.setText("Data Nasc.:");

        } catch (Exception e){}
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCPFLayout = new javax.swing.GroupLayout(panelCPF);
        panelCPF.setLayout(panelCPFLayout);
        panelCPFLayout.setHorizontalGroup(
            panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCPFLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxRG, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCPFLayout.setVerticalGroup(
            panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCPFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(boxRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCPFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDados.add(panelCPF);
        panelCPF.setBounds(70, 90, 440, 34);
        panelCPF.setVisible(false);

        boxCPF_CNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCPF_CNPJActionPerformed(evt);
            }
        });
        panelDados.add(boxCPF_CNPJ);
        boxCPF_CNPJ.setBounds(90, 60, 420, 20);

        radioTipoPessoa.add(radioCNPJ);
        radioCNPJ.setSelected(true);
        radioCNPJ.setText("CNPJ");
        radioCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCNPJActionPerformed(evt);
            }
        });
        panelDados.add(radioCNPJ);
        radioCNPJ.setBounds(10, 60, 70, 21);

        radioTipoPessoa.add(radioCPF);
        radioCPF.setText("CPF");
        radioCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCPFActionPerformed(evt);
            }
        });
        panelDados.add(radioCPF);
        radioCPF.setBounds(10, 80, 70, 21);

        jPanel1.setLayout(null);

        boxUF.setEditable(false);
        boxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUFActionPerformed(evt);
            }
        });
        jPanel1.add(boxUF);
        boxUF.setBounds(35, 5, 40, 20);

        jLabel7.setText("UF:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 5, 30, 16);

        jLabel8.setText("Cidade:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 5, 50, 16);

        boxCidade.setEditable(false);
        boxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(boxCidade);
        boxCidade.setBounds(130, 5, 160, 22);

        jLabel9.setText("Bairro:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 10, 50, 16);

        boxBairro.setEditable(false);
        jPanel1.add(boxBairro);
        boxBairro.setBounds(350, 5, 140, 22);

        jLabel10.setText("Logradouro:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 40, 80, 16);

        boxLogradouro.setEditable(false);
        jPanel1.add(boxLogradouro);
        boxLogradouro.setBounds(90, 40, 400, 22);

        panelDados.add(jPanel1);
        jPanel1.setBounds(10, 230, 500, 70);

        add(panelDados);
        panelDados.setBounds(6, 6, 520, 310);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });
        add(buttonCancelar);
        buttonCancelar.setBounds(120, 325, 100, 37);

        buttonCadastrar.setLabel("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        add(buttonCadastrar);
        buttonCadastrar.setBounds(310, 325, 110, 37);

        buttonBuscarEm.setText("Buscar Emp.");
        buttonBuscarEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarEmActionPerformed(evt);
            }
        });
        add(buttonBuscarEm);
        buttonBuscarEm.setBounds(20, 330, 80, 30);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:
        Locale locale = new Locale("pt","BR");
        JOptionPane.setDefaultLocale(locale);
        
        UIManager.put("OptionPane.cancelButtonText", "Cancelar");
        UIManager.put("OptionPane.noButtonText", "Não");
        UIManager.put("OptionPane.okButtonText", "OK");
        UIManager.put("OptionPane.yesButtonText", "Sim");
    
        int input = JOptionPane.showConfirmDialog(null, "Deseja cancelar o cadastro de fornecedor?", "Seleção de empresas", JOptionPane.YES_NO_OPTION);
        switch(input) {
            case 0:
                this.setEnabled(false);
                break;
            case 1, 2:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void boxCPF_CNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCPF_CNPJActionPerformed
        // TODO add your handling code here:
        System.out.println("formatado: " + this.boxCPF_CNPJ.getText());
//        try{
//            System.out.println("BlocoA: " + this.boxCNPJ_CPF.getText().length());
//        }catch (java.text.ParseException p){
//            System.out.println("BlocoB: " + this.boxCNPJ_CPF.getText().length());
//        } finally{
//            
//        }
    }//GEN-LAST:event_boxCPF_CNPJActionPerformed

    private void boxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNomeActionPerformed

    private void radioCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCNPJActionPerformed
        // TODO add your handling code here:
        panelCPF.setVisible(false);
        try {
            boxCPF_CNPJ.setFormatterFactory(
                new DefaultFormatterFactory(
                    new MaskFormatter("##.###.###/####-##")));
                    boxCPF_CNPJ.setValue(null);
        } catch (java.text.ParseException e) {
        }
    }//GEN-LAST:event_radioCNPJActionPerformed

    private void radioCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCPFActionPerformed
        // TODO add your handling code here:
        panelCPF.setVisible(true);
        try {
            boxCPF_CNPJ.setFormatterFactory(
                new DefaultFormatterFactory(
                    new MaskFormatter("###.###.###-##")));
            boxCPF_CNPJ.setValue(null);
        } catch (java.text.ParseException e) {
        }
    }//GEN-LAST:event_radioCPFActionPerformed

    private void boxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxUFActionPerformed

    private void boxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxCidadeActionPerformed

    private void boxCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCEPActionPerformed
        // TODO add your handling code here:
        try{
            ControllerUtils utilitario = new ControllerUtils();
            JSONObject endereco = utilitario.coletarEndereco(this.boxCEP.getText());
            
            boxUF.setText((String) endereco.get("uf"));
            boxUF.setEditable(false);
            
            boxCidade.setText((String) endereco.get("cidade"));
            boxCidade.setEditable(false);
            
            boxBairro.setText((String) endereco.get("bairro"));
            boxBairro.setEditable(false);
            
            boxLogradouro.setText((String) endereco.get("logradouro"));
            boxLogradouro.setEditable(false);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_boxCEPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
        System.out.println(this.txtData.getText());
    }//GEN-LAST:event_txtDataActionPerformed

    private void buttonBuscarEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarEmActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new GUIBuscarEmpresa(this.txtData.getText()).setVisible(true);
    }//GEN-LAST:event_buttonBuscarEmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog alertaCancelar;
    private javax.swing.JTextField boxBairro;
    private javax.swing.JTextField boxCEP;
    private javax.swing.JFormattedTextField boxCPF_CNPJ;
    private javax.swing.JTextField boxCidade;
    private javax.swing.JTextField boxEmail;
    private javax.swing.JTextField boxLogradouro;
    private javax.swing.JTextField boxNome;
    private javax.swing.JTextField boxRG;
    private javax.swing.JTextField boxUF;
    private javax.swing.JButton buttonBuscarEm;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lcep;
    private javax.swing.JLabel lemail;
    private javax.swing.JPanel panelAlerta;
    private javax.swing.JPanel panelCPF;
    private javax.swing.JPanel panelDados;
    private javax.swing.JRadioButton radioCNPJ;
    private javax.swing.JRadioButton radioCPF;
    private javax.swing.ButtonGroup radioTipoPessoa;
    private javax.swing.JFormattedTextField txtData;
    // End of variables declaration//GEN-END:variables
}
