/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author User
 */
public class GUIInicial extends javax.swing.JFrame {

    /**
     * Creates new form GUIInicial
     */
    public GUIInicial() {
        cad_Fornecedor  = new GUICadFornecedor();
        //secondPanel     = new GUIAdicionarEmpresa();
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        //principalPanel.add(secondPanel, "AdicionarEmpresa");
        principalPanel.add(cad_Fornecedor, "CadastrarFornecedor");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpresa = new javax.swing.JMenu();
        menuAddEm = new javax.swing.JMenuItem();
        menuLookEm = new javax.swing.JMenuItem();
        menuFornecedor = new javax.swing.JMenu();
        menuAddForn = new javax.swing.JMenuItem();
        menuLookForn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Desafio FullStack 1.0");
        setPreferredSize(new java.awt.Dimension(570, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(570, 450));

        principalPanel.setPreferredSize(new java.awt.Dimension(530, 450));
        principalPanel.setLayout(new java.awt.CardLayout());

        menuEmpresa.setText("Empresa");

        menuAddEm.setText("Adicionar...");
        menuAddEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddEmActionPerformed(evt);
            }
        });
        menuEmpresa.add(menuAddEm);

        menuLookEm.setText("Buscar...");
        menuEmpresa.add(menuLookEm);

        jMenuBar1.add(menuEmpresa);

        menuFornecedor.setText("Fornecedor");

        menuAddForn.setText("Adicionar...");
        menuAddForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddFornActionPerformed(evt);
            }
        });
        menuFornecedor.add(menuAddForn);

        menuLookForn.setText("Buscar...");
        menuFornecedor.add(menuLookForn);

        jMenuBar1.add(menuFornecedor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddEmActionPerformed
        // TODO add your handling code here:
        //principalPanel.setVisible(false);
//        secondPanel.setVisible(true);
        CardLayout c1 = (CardLayout) principalPanel.getLayout();
        c1.show(principalPanel, "AdicionarEmpresa");
        
        //principalPanel.add(secondPanel);
        
        //second.setVisible(true);
        
    }//GEN-LAST:event_menuAddEmActionPerformed

    private void menuAddFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddFornActionPerformed
        // TODO add your handling code here:
//        principalPanel.add(cad_Fornecedor);
        CardLayout c2 = (CardLayout) principalPanel.getLayout();
        c2.show(principalPanel, "CadastrarFornecedor");

    }//GEN-LAST:event_menuAddFornActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    GUIInicial inicio = new GUIInicial();
                    inicio.setVisible(true);
                    new GUIInicial().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GUIInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //private final GUIAdicionarEmpresa add_Empresa;
    private final GUICadFornecedor cad_Fornecedor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddEm;
    private javax.swing.JMenuItem menuAddForn;
    private javax.swing.JMenu menuEmpresa;
    private javax.swing.JMenu menuFornecedor;
    private javax.swing.JMenuItem menuLookEm;
    private javax.swing.JMenuItem menuLookForn;
    private javax.swing.JPanel principalPanel;
    // End of variables declaration//GEN-END:variables
}
